// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDD2uu_eYZ0WJPu1MlSDOZO9Iw15TG5Y',
    appId: '1:590116494094:web:01231cc9d7f00f6149555f',
    messagingSenderId: '590116494094',
    projectId: 'finalprojectamona',
    authDomain: 'finalprojectamona.firebaseapp.com',
    storageBucket: 'finalprojectamona.firebasestorage.app',
    measurementId: 'G-0CZ59NL77V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiORu4RZKYKq_lIfdH_n6MuSExZ-9bPQI',
    appId: '1:590116494094:android:b34a0e5b1f6ceb3949555f',
    messagingSenderId: '590116494094',
    projectId: 'finalprojectamona',
    storageBucket: 'finalprojectamona.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC2aNLp72ll8Ra2tRFwY4toW_k_Sc_qEY',
    appId: '1:590116494094:ios:b09efa6d81287afa49555f',
    messagingSenderId: '590116494094',
    projectId: 'finalprojectamona',
    storageBucket: 'finalprojectamona.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectAmona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC2aNLp72ll8Ra2tRFwY4toW_k_Sc_qEY',
    appId: '1:590116494094:ios:b09efa6d81287afa49555f',
    messagingSenderId: '590116494094',
    projectId: 'finalprojectamona',
    storageBucket: 'finalprojectamona.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectAmona',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyDD2uu_eYZ0WJPu1MlSDOZO9Iw15TG5Y',
    appId: '1:590116494094:web:11f78f54a058126749555f',
    messagingSenderId: '590116494094',
    projectId: 'finalprojectamona',
    authDomain: 'finalprojectamona.firebaseapp.com',
    storageBucket: 'finalprojectamona.firebasestorage.app',
    measurementId: 'G-51YD62RF8J',
  );
}
