import 'package:final_project_amona/splach_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'auth_screen.dart';
import 'firebase_options.dart'; // Ensure this file is generated by flutterfire configure
import 'package:firebase_auth/firebase_auth.dart'; // Import for checking auth state
import 'home_screen.dart';


void main() async {
  // Ensure Flutter widgets are initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the generated options for the current platform
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Social App Clone',
      debugShowCheckedModeBanner: false, // Remove debug banner
      theme: ThemeData(
        primarySwatch: Colors.blue,
        // Define a consistent font family for the app
        fontFamily: 'Inter', // Assuming you'll add Inter font, otherwise remove
        visualDensity: VisualDensity.adaptivePlatformDensity,
        // Apply rounded corners to elevated buttons
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12.0), // Rounded corners for buttons
            ),
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            textStyle: const TextStyle(fontSize: 16),
          ),
        ),
        // Apply rounded corners to text form fields
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12.0), // Rounded corners for input fields
            borderSide: BorderSide.none, // No border by default
          ),
          filled: true,
          fillColor: Colors.blue.shade50, // Light blue background for inputs
          contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        ),
        cardTheme: CardTheme(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(15.0), // Rounded corners for cards
          ),
          elevation: 3,
          margin: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
        ),
      ),
      // Use a FutureBuilder to check authentication state and navigate accordingly
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          // Show splash screen while checking auth state
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const SplashScreen();
          }
          // If user is logged in, go to HomeScreen
          if (snapshot.hasData && snapshot.data != null) {
            return const HomeScreen(); // Navigate to HomeScreen if authenticated
          }
          // If no user is logged in, go to AuthScreen
          return const AuthScreen(); // Navigate to AuthScreen if not authenticated
        },
      ),
    );
  }
}
